apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: frontend-secret
  namespace: vao
spec:
  encryptedData:
    SENTRY_AUTH_TOKEN: AgCjxDrLQipfzznbADdam0DScbnulIoGcAjzcujTKMioyvSoOkIHmpPfhhvPrk3I5mRmET6pKzi12An6/ydPNvAht+4Fp8w+023NjK20UPGaAbJ5T9ksw53DaBkHF3npEl9IWr+zhv+xVw5nQuUKBgP6NZIUo57kgttTDq5noT2dBRTvArbA1FFQlnNF/ofLO3LI0pvq2nrHK/Ick0AvNFergsbGSIsw4ELdZ4zV6bnx8hut8t1oXHm0tYpYdvnGWqu/zbgelGdUBduZRXNOnR+XufgHd9HiWDn0J4eYgT8ZXMzNZ/7HKjN2Z6qQdKXQ5bbwljivnGfvnmY4xWd20aqAW9hBQPqXOrho5X8qRT9805ulfBb+Tji7CUHiqLd5gzEsRGpTct2H35X89NzrqDpd39vH6EQs2a/vvfmL9gT+xVtHEW3giojGY5WRED62TQJzLtSNuu8ZaDfVpdN8oUVzGg13wQBKfCa0XWoasc8oUWIHV91s0TM2OIYpXG8j0Tf8VMg0LX5can4W8yupVJGNF64Uo8xF92391WIvbbL1/DhyBdJcegjBmql1t7lWIyzYkeSEmh+vDrB+trimhonCZ+aRdP6sA9zAYGFstq+6gBCPIQZBc9ychFM4BDQ7p/4SFoK1aPYCZdkKTEYVMZfitx1wCNNTPl++VMV0DiwIItq9AvRnzla+sw80w2Cnr8gWakNXzdh9tjrWo82+b5Ax5nhfcUaSadhpmBxlrSL/7uIyJOVNki4k580j8N9iOuZVZpYYan0HnyPdXvx2Hmcf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: frontend-secret
    type: Opaque
