apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: token
  namespace: vao
spec:
  encryptedData:
    TOKEN_SECRET: AgB99GRNXcXoa/2Yybf+Vv5J9KzOzig4JEtuGM86QLkR+nSSvs7bGdMczyDKKrpL97BB/vsb8YS4ReviQFjifS9g7MoejeXTTM9KrTldYBcz/v9ylbdYfwmakMxoeoaUbZt95f4DMs7D7mFrz2cJOyAq/H6BdR3AGPhUpiQ+3cyYm6OWzalQFO8YTbj1ma3IBAfHL+eNQ8UU8fIALtd8alpafex1T3/szllbHazBkHkrvrgM1OPs7Qr9dsyYDnyCjX3YyeC7jVFF2zjWIFMhMmYwhUFgNJdLWGmXMyJI7rkoHpQqj9UGqnHxLUbOJyok7r68uoKnOMjIb5RRUaLj5x4O6IslHWWyXyvguF8AbgKgWA1BxBf9B62CXnBHDcJhZ1prBQXjF33BxwqM7LAQp6p29d7XXVcOxNQ4aglYN7Ah0Kj7WKLQ+Hjmz8Wa87ni9gUL/E47IQMQP+CthzJzepky2+Lm503oln8ksRCg/6hyX2CdHsob5gMoRoFpWzphGv9buiffm6eWPLHpaLE+lSubQh70YsnKMf+Vs37nEBZie7uPoFJRCtqTGQZHi9x3cDN3gIuyfE8CDM6+72+hHdwO+9wTCme9iivL1jC6HpFzkR4l5eamd8QSNcuuG8/pHIqbtYxhUknekzAlPUPBCiwe3SQx5JWccXKQ2lm/Ig0rDjf2ZEkOc1m94NeNKQbPM0e9xyRfo74BD1v+0b/HwvdBmdjhXV6lIqFFIvOJRUKHjkZ5NYWzetvEvbgfItEgjJ1bmWcKU7z2wxBiHKHY9ENxiKZyvp53QI5Y9YXqUCr+r9lpGKn5EiigYiGWoKrS5EZWiBVuk08Bt1oz9PzEkA5gwYmkjh2T30vI+oAXjXqPxULd5OLpDuC5ZQ9LId8sm4t1WmnaLSN7DkhhdjyNX0Le+VeYjyGuuf4a/3goxsgu0zMjFJmTqnLcwOh+aySTeh0kjlEHeKA13I7c/8XzNmUpgssDFXRt+bFJpWWXdtjZetZr1MBM8u+H+Xi47xIDjBIjojKs+N1zvKCJeLp5UfaOhbAiQxF9TSzvXu2POWmyjIhXj5lU5BfraICiB0bJGrMTw4RY4HMqyQ97lt5D7r2oHjN/rETvC1X+oV6e7y0744UWYNGNLEplUm7RYIl3xVkhGQXwRE4fFNMMVhkdtX+All1ntJC/NJo4LBVx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: token
    type: Opaque
