jobs:
  runs:
    build-frontend-usagers:
      with:
        buildArgs:
          NUXT_PUBLIC_APP_VERSION: "{{ .Values.global.gitBranch }}"
          NUXT_PUBLIC_ENVIRONMENT: "production"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
    build-frontend-bo:
      with:
        buildArgs:
          NUXT_PUBLIC_APP_VERSION: "{{ .Values.global.gitBranch }}"
          NUXT_PUBLIC_ENVIRONMENT: "production"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"