maildev: {}

pgweb:
  ~chart: pgweb
  pgweb:
    env:
      - name: PGWEB_DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: pg-app
            key: DATABASE_URL
    ingress:
      enabled: false
    oauth2-proxy:
      enabled: true
      host: pgweb-{{ .Values.global.host }}
      config:
        OAUTH2_PROXY_GITHUB_ORG: "SocialGouv"
        OAUTH2_PROXY_GITHUB_TEAM: "admins-vao,sre"
      envFrom:
        - secretRef:
            name: oauth2-proxy

pg:
  backup:
    name: "202407181635" # backup on a new folder

jobs:
  runs:
    build-frontend-usagers:
      with:
        buildArgs:
          NUXT_PUBLIC_APP_VERSION: "{{ .Values.global.gitBranch }}"
          NUXT_PUBLIC_ENVIRONMENT: "preprod"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
    build-frontend-bo:
      with:
        buildArgs:
          NUXT_PUBLIC_APP_VERSION: "{{ .Values.global.gitBranch }}"
          NUXT_PUBLIC_ENVIRONMENT: "preprod"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
