apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: api-insee
spec:
  encryptedData:
    API_INSEE_CLIENT_ID: AgA1FhEJw8Ff7BqSQJI9U7zcHFX8cJhkw6Vbv+iADb6IRkuMLcVzo//YE7uQKGJLeXZPFkOBkBE5IhQ5TSAE3sXwxLqoHN6gJh8p9HtjYMPC8b3gem7fXkXw1eyAH2NwRSQw4M63Jud/BZB5X3A9pr+kP+HrvTscuaVD/8vJOfGlukZJ+pWlr8+8F0+TlBUjXDqzqlJmRS5JZ4s7gpcK3Rl8pImrAcfpzCkBrDm+ON2U4HjnVRdaJUNYzSI//GeryySEwkYSD6j1odRDj3m/Un3nJtsxGFxjC1KODxWWF6cvq/u3mm9cyGQ6oaZql/nLS54rboVQBeRvJSL0Ny8m1XiI1QMWLlCWYIh6bBFiAgE+Xw/8IX7oM1bwaC2PXISUJB+8MeBf3SvZp31iBuBMDSBfCC5RhPh07W3gut49XLmZwbWX5G+5Y5eOLl19QQUZD4K/ZYSBj/jcfVsNMpFxupih0AL0c7arsOWagfa8LYoawfvVs323W3JayRGcJn0WI4bpxMO9pwp16bqSMu7HThkKDRxqjKAXWLLWTa1pOYqQnh0thY6qitDjLvfx9RAL2/PFQpqwZZlTUscYb6ySZlV9AmObQgyyNIeCxY8kQ6YRBXEBmIRA8HkevIpsgNwvsZEE5tKGLEQg/NG6WKC6IamOQG3VVWRHpSk+0ECHUAP1hyddGucwJUVANV3GsYD06WOjklsgAml6yuQI/OcZLyG5W7M/bMv/fm7IQPhD
    API_INSEE_CLIENT_SECRET: AgBk0R1VHrlim8j5zm5wG0orVVsVkxmA379KBoa8nYq+nyLvAiIC2Kn+iQ8y+e780A7Zrb6cU3DCI5IcvLDn4btqpvFitRDKR8Jk8VpAGxLMXwGTuXZdmEPR3aZNv6nBcKtKfzO1CbK/Oq/kUMnITrdbcAaPN+Oo3tBFyZJaMEbyGDE6Tmt1fTY5Voag3cdpUdzJPVb6B3H3MTK1RVvLE01woOz74j4QU7NRKkmCfD5IXdzcI/wqna6n3rkjxxZdZScRME8/PeSF0lNuvIBAlWbyjQLDUSei9A8aIvAs0hggaELwCtHlGqNc7+sG6OFb43irOB33zk+dH57fN1n3kFu6Q4NdTWETAi6ae5pxLBnZpXBhNp/R5FyqNdBUtZnvISea2aZpuMGZd3pLp+W1R7WU+RpgPbTrpixMiSsUMLmg3uVfKdHU2tPFP+q2e6nwlnYQa/rEQ8I9IVbFWMa5+z3faXTyVRU9WkvhbLCeuAve7DzirnoZQ7l9izrCsso1IaWqF2hvTW+Jh6sgJThCaJI79brUQtMfsFB2h21oPxhH9OBEOarmKTd0cDQM4a/xd35Oq4A150JuiRgSP93JvnPpz/7tmt4c0ni1lzI8I3C6wy9CuHjpToMOGLTQnFfF7qBEIJVHHHCReZcKMA8rCIffNsVxeyXvK77gCYej+drHqun4JREOKIKMuGZBSEbG0PHBPMmMYGOi4gRmOb8nDjhECna7tYA3+ibzgwyH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: api-insee
    type: Opaque
