projectName: vao
ciNamespace: ci-vao

dependencies:
  fabrique:
    extends:
      - name: ovh
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                harbor-pull-secret:
                vao-dev-backups-access-key:
                vao-prod-backups-access-key:
